name: auto-semver-actions
on: [push]
env:
  GITHUB_URL: 'git@github.com:RightBrain-Networks/auto-semver.git'
  GITHUB_KEY: 'rbn-ops github'

  SERVICE: 'auto-semver'
  SELF_SEMVER_TAG: "master"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install auto-semver
          pip install -e .
      - name: Set up Python ${{ matrix.python-version }}
        run: python setup.py sdist
      - name: Test
        run: |
          python tests.py
        with:
          working-directory: semver
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false