name: auto-semver-actions
on: [push]
env:
  GITHUB_URL: 'git@github.com:RightBrain-Networks/auto-semver.git'
  GITHUB_KEY: 'rbn-ops github'

  SERVICE: 'auto-semver'
  SELF_SEMVER_TAG: "master"
jobs:
  self-version:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install auto-semver
      - run: pip3 install -e .
  build:
    runs-on: ubuntu-latest
    needs: self-version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: python setup.py sdist
  test:
    runs-on: ubuntu-latest
    needs: [self-version, build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: python semver/tests.py
  push:
    runs-on: ubuntu-latest
    needs: [self-version, build, test]
    steps:
      - uses: actions/checkout@v2
      - run: aws s3 cp `ls -t ./dist/semver-* | head -1` s3://rbn-ops-pkg-us-east-1/${env.SERVICE}/${env.SERVICE}-${env.VERSION}.tar.gz
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish release
        uses: auto-semver/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}